### PR TITLE
Support VeSync In Wall Switches

### PR DESCRIPTION
**Pull request by mattbat**
Joe,
Thanks for picking up development on this project again.

I've added support for the "In Wall" variant of the VeSync Wifi switches (https://www.etekcity.com/productcate/121/list)

These switches utilize a slightly different API and (from what I've seen) only support On and Off commands (no ability to read voltage or power)

I'm not really sure how to test the Home Assistant custom component.  I'm new to Home Assistant and was unsuccessful in adding the custom component to my HA instance.  If I can figure that piece out, I'm happy to update the HA component to support the In Wall switches.

### CODE REVIEW

**Comment by mattbat** [comment]
I updated the HA custom component, but wasn't able to figure out how to import the updated vesync-2 library during development.

I went ahead and copied this file to the same directory as the HA custom component and imported it from teh current directory (".").  This shouldn't be merged, but I wanted to show how I expected the rest of the HA component to work.

I tested this custom component in HA 0.88.0 and was able to control the in wall switches

**Comment by webdjoe** [comment]
Hi Matt, thanks for the PR!  I have been working on a major update to support both of the new switches and streamline the code to make integration easier for future devices.  I should have it out tonight as well as the PR to integrate it into HA.  I will also have the pip package updated so there is no need to include the script in custom_components, just the component with the requirement specified.

**Comment by mattbat** [comment]
Great!  Looking forward to it

**Comment by webdjoe** [comment]
Support for switches released in current branch.

**Comment by webdjoe** [comment]
Wall Switch added

**Pull request closed without merging**
